export const routes = [
  { path: '/auth/account-deactivation-basic', title: 'Account Deactivation' },
  {
    path: '/auth/account-deactivation-creative',
    title: 'Account Deactivation',
  },
  { path: '/auth/account-deactivation-modern', title: 'AccountDeactivation' },
  { path: '/auth/forgot-password-basic', title: 'Forgot Password' },
  { path: '/auth/forgot-password-creative', title: 'Forgot Password' },
  { path: '/auth/forgot-password-modern', title: 'Forgot Password' },
  { path: '/auth/reset-password-basic', title: 'Reset Password' },
  { path: '/auth/reset-password-creative', title: 'Reset Password' },
  { path: '/auth/reset-password-modern', title: 'Reset Password' },
  { path: '/auth/login', title: 'SignIn' },
  { path: '/auth/signin-creative', title: 'SignIn' },
  { path: '/auth/signin-modern', title: 'SignIn' },
  { path: '/auth/signup-basic', title: 'SignUp' },
  { path: '/auth/signup-creative', title: 'SignUp' },
  { path: '/auth/signup-modern', title: 'SignUp' },
  {
    path: '/auth/two-step-verification-creative',
    title: 'Two Step Verification',
  },
  {
    path: '/auth/two-step-verification-modern',
    title: 'Two Step Verification',
  },
  { path: '/auth/two-step-verification-basic', title: 'Two Step Verification' },
  { path: '/auth/successful-password-basic', title: 'Successful Password' },
  { path: '/auth/successful-password-creative', title: 'Successful Password' },
  { path: '/auth/successful-password-modern', title: 'Successful Password' },
  { path: '/page/contact-us', title: 'Contact Us' },
  { path: '/page/coming-soon', title: 'Coming Soon' },
  { path: '/page/maintenance', title: 'Maintenance' },
  { path: '/page/404', title: '404' },
  { path: '/page/500', title: '500' },
  { path: '/page/contact-us-five', title: 'Contact Us' },
  { path: '/page/contact-us-four', title: 'Contact Us' },
  { path: '/page/contact-us-three', title: 'Contact Us' },
  { path: '/page/contact-us-two', title: 'Contact Us' },
  {
    path: '/apps/email/templates/newsletter',
    title: 'NewsLetter Email Template',
  },
  { path: '/apps/email/templates/welcome', title: 'Welcome Email Template' },
  { path: '/landing/doctors', title: 'Doctors' },
  { path: '/landing/ecommerce', title: 'Ecommerce' },
  { path: '/landing/email', title: 'Email' },
  { path: '/landing/invoice', title: 'Invoice' },
  { path: '/landing/school', title: 'School' },
  { path: '/apps/projects', title: 'ProjectsGrid' },
  { path: '/apps/calendar/date-clicking', title: 'Date Clicking & Selecting' },
  { path: '/apps/calendar/date-nav-link', title: 'Date Nav Link' },
  { path: '/apps/calendar/dayview', title: 'Day Grid View' },
  { path: '/apps/calendar/default', title: 'Default' },
  { path: '/apps/calendar/listview', title: 'List View' },
  { path: '/apps/calendar/localize', title: 'Localize' },
  { path: '/apps/calendar/multi-month-grid', title: 'Multi-Month grid' },
  { path: '/apps/calendar/multi-month-stack', title: 'Multi-Month Stack' },
  { path: '/apps/calendar/timegrid', title: 'Time Grid View' },
  { path: '/apps/calendar/timeline', title: 'Timeline' },
  { path: '/apps/calendar/weeknumber', title: 'Week Number' },
  { path: '/apps/chat/default', title: 'Default Chat' },
  { path: '/apps/chat/group', title: 'Group Chat' },
  { path: '/apps/chat/video', title: 'Group Video' },
  { path: '/apps/crm/contact', title: 'Contact' },
  { path: '/apps/crm/deal', title: 'Deals' },
  { path: '/apps/crm/lead', title: 'Leads' },
  { path: '/apps/ecommerce/category', title: 'Category List' },
  { path: '/apps/ecommerce/wishlist', title: 'Wishlist' },
  { path: '/apps/ecommerce/checkout', title: 'Checkout' },
  { path: '/apps/ecommerce/customer/list', title: 'List View' },
  { path: '/apps/ecommerce/customer/user', title: 'User Overview' },
  { path: '/apps/ecommerce/manage-reviews', title: 'Manage Reviews' },
  { path: '/apps/ecommerce/orders/list', title: 'Order List' },
  { path: '/apps/ecommerce/orders/track', title: 'Order Track' },
  { path: '/apps/ecommerce/orders/overview', title: 'Orders Overview' },
  { path: '/apps/ecommerce/payment', title: 'Payment' },
  { path: '/apps/ecommerce/products/category', title: 'Category List' },
  { path: '/apps/ecommerce/products/create-products', title: 'Create Product' },
  { path: '/apps/ecommerce/products/grid', title: 'Product Grid' },
  { path: '/apps/ecommerce/products/list', title: 'Product List' },
  { path: '/apps/ecommerce/products/overview', title: 'Product Overview' },
  { path: '/apps-ecommerce/shop-cart', title: 'Shop Cart' },
  { path: '/apps-ecommerce/wishlist', title: 'Wishlist' },
  { path: '/apextree/bottom-top', title: 'Bottom to Top' },
  { path: '/apextree/collapse-expand', title: 'Collapse Expand' },
  { path: '/apextree/left-right', title: 'Left to Right' },
  { path: '/apextree/right-left', title: 'Right To Left' },
  { path: '/apextree/top-bottom', title: 'Top To Bottom' },
  { path: '/apps/email/template/welcome', title: 'Welcome' },
  { path: '/apps/events/grid', title: 'Grid List' },
  { path: '/apps/events/list', title: 'List View' },
  { path: '/apps/events/overview', title: 'Overview' },
  { path: '/apps/file-manager', title: 'File Manager' },
  { path: '/apps/hospital/appointments-book', title: 'Book' },
  { path: '/apps/hospital/appointments-lists', title: 'List View' },
  { path: '/apps/hospital/departments', title: 'Departments' },
  { path: '/apps/hospital/doctor-schedule', title: 'Doctor Schedule' },
  { path: '/apps/hospital/patients-create', title: 'Create Patients' },
  { path: '/apps/hospital/patients-lists', title: 'List View' },
  { path: '/apps/hospital/patients-overview', title: 'Overview' },
  { path: '/apps/hospital/payroll-employee-salary', title: 'Employee Salary' },
  { path: '/apps/hospital/payroll-payslip', title: 'Payslip' },
  { path: '/apps/hospital/staff-attendance', title: 'Attendance' },
  { path: '/apps/hospital/staff-holidays', title: 'Holidays' },
  { path: '/apps/hospital/staff-leave-add', title: 'Staff Leave' },
  { path: '/apps/hospital/staff-leaves', title: 'Add Leaves' },
  { path: '/apps/hospital/staff-lists', title: 'List View' },
  { path: '/apps/invoice/create', title: 'Create Invoice' },
  { path: '/apps/invoice/grid', title: 'Grid View' },
  { path: '/apps/invoice/list', title: 'List View' },
  { path: '/apps/invoice/overview-1', title: 'Overview' },
  { path: '/apps/invoice/overview-2', title: 'Overview' },
  { path: '/apps/mailbox', title: 'Mailbox' },
  { path: '/apps/projects/files', title: 'Projects Files' },
  { path: '/apps/projects/grid', title: 'Projects Grid' },
  { path: '/apps/projects/list', title: 'Projects List' },
  { path: '/apps/projects/overview', title: 'Projects Overview' },
  { path: '/apps/projects/roadmap', title: 'Projects Roadmap' },
  { path: '/apps/projects/task', title: 'Projects Task' },
  { path: '/apps/projects/users', title: 'Projects Users' },
  { path: '/apps/school/exam-question', title: 'Exam Question' },
  { path: '/apps/school/exam-schedule', title: 'Exam Schedule' },
  { path: '/apps/school/library-book', title: 'Library Book' },
  { path: '/apps/school/parents', title: 'School Parents' },
  { path: '/apps/school/students-admission', title: 'Students Admission' },
  { path: '/apps/school/students-list', title: 'Students List' },
  { path: '/apps/school/students-overview', title: 'Students Overview' },
  { path: '/apps/school/teachers-list', title: 'List View' },
  { path: '/apps/school/teachers-overview', title: 'Overview' },
  { path: '/apps/school/teachers-payroll', title: 'Payroll' },
  { path: '/dashboards/analytics', title: 'Analytics ' },
  { path: '/dashboards/music', title: 'Music' },
  { path: '/dashboards/crm', title: 'CRM' },
  { path: '/dashboard', title: 'Dashboard' },
  { path: '/dashboards/school', title: 'School' },
  { path: '/dashboards/email', title: 'Email ' },
  { path: '/dashboards/projects', title: 'Projects ' },
  { path: '/dashboards/file-manager', title: 'File Manager ' },
  { path: '/dashboards/hospital', title: 'Hospital ' },
  { path: '/form/basic-input', title: 'Basic Input' },
  { path: '/form/input-group', title: 'Input Group' },
  { path: '/form/checkbox-radio', title: 'Checkbox & Radio' },
  { path: '/form/file-input', title: 'File Input' },
  { path: '/form/select', title: 'Select' },
  { path: '/form/pickers', title: 'Pickers' },
  { path: '/form/range', title: 'Range' },
  { path: '/form/switches', title: 'Switches' },
  { path: '/form/input-spin', title: 'Spin' },
  { path: '/form/recaptcha', title: 'ReCaptcha' },
  { path: '/form/autosize', title: 'Autosize' },
  { path: '/form/clipboard', title: 'Clipboard' },
  { path: '/table/base', title: 'Base Table' },
  { path: '/icons/lucide', title: 'Lucide Icon' },
  { path: '/icons/remix', title: 'Remix Icon' },
  { path: '/icons/heroicons', title: 'Hero Icon' },
  { path: '/icons/boxicon', title: 'Box Icon' },
  { path: '/icons/line-awesome', title: 'Line Awesome Icon' },
  { path: '/table/base', title: 'Base Table' },
  { path: '/table/datatables/basic', title: 'Basic DataTables' },
  { path: '/table/datatables/bordered', title: 'Bordered DataTables' },
  { path: '/table/datatables/enable-disable', title: 'Enable Datatables' },
  { path: '/table/datatables/hover', title: 'Hover DataTables' },
  { path: '/table/datatables/row-grouping', title: 'Row Grouping DataTables' },
  { path: '/table/datatables/stripe', title: 'Stripe DataTables' },
  { path: '/ui/accordion', title: 'Accordion' },
  { path: '/ui/advanced-3d-effect', title: '3d Effect' },
  { path: '/ui/advanced-animation', title: 'Animation' },
  { path: '/ui/advanced-bot', title: 'Bot' },
  { path: '/ui/advanced-highlight', title: 'Highlight Code' },
  { path: '/ui/advanced-image-annotation', title: 'Image Annotation' },
  { path: '/ui/advanced-mask', title: 'Mask Input' },
  { path: '/ui/advanced-simplebar', title: 'Simplebar' },
  { path: '/ui/advanced-swiper', title: 'Swiper' },
  { path: '/ui/advanced-tree', title: 'Tree' },
  { path: '/ui/advanced-word-counter', title: 'Word Counter' },
  { path: '/ui/alerts', title: 'Alerts' },
  { path: '/ui/badge', title: 'Badge' },
  { path: '/ui/breadcrumb', title: 'Breadcrumb' },
  { path: '/ui/button-navigation', title: 'Badge' },
  { path: '/ui/button-group', title: 'Button Navigation ' },
  { path: '/ui/buttons', title: 'Buttons' },
  { path: '/ui/cards', title: 'Cards' },
  { path: '/ui/colors', title: 'Colors' },
  { path: '/ui/cookie', title: 'Cookie' },
  { path: '/ui/drawer', title: 'Drawer' },
  { path: '/ui/dropdown', title: 'Dropdown' },
  { path: '/ui/gallery', title: 'Gallery' },
  { path: '/ui/links', title: 'Links' },
  { path: '/ui/list-group', title: 'List Group' },
  { path: '/ui/loader', title: 'Loader' },
  { path: '/ui/notification', title: 'Notification' },
  { path: '/ui/pagination', title: 'Pagination' },
  { path: '/ui/progress-bar', title: 'Progress Bar' },
  { path: '/ui/timeline', title: 'Timeline' },
  { path: '/ui/tooltips', title: 'Tooltips' },
  { path: '/ui/video', title: 'Video' },
  { path: '/ui/buttons-group', title: 'Buttons Group' },
  { path: '/ui/modal', title: 'Modal' },
  { path: '/ui/tabs', title: 'Tabs' },
  { path: '/ui/typography', title: 'Typography' },
  { path: '/widgets/banners', title: 'Banners' },
  { path: '/widgets/cards', title: 'Cards' },
  { path: '/widgets/charts', title: 'Charts' },
  { path: '/widgets/data', title: 'Data' },
  { path: '/apps/school/attendances-students', title: 'Attendances' },
  { path: '/page/starter', title: 'Starter' },
  { path: '/page/account-settings', title: 'Account Settings' },
  { path: '/page/account-security', title: 'Account Security' },
  { path: '/page/account-billing-plan', title: 'Account Billing Plan' },
  { path: '/page/account-notification', title: 'Account Notification' },
  { path: '/page/account-statements', title: 'Account Statements' },
  { path: '/page/account-logs', title: 'Account Logs' },
  { path: '/page/user-projects', title: 'User Projects' },
  { path: '/page/user-notes', title: 'User Notes' },
  { path: '/page/user-documents', title: 'User Documents' },
  { path: '/page/user-followers', title: 'User Followers' },
  { path: '/page/user-activity', title: 'User Activity' },
  { path: '/page/user', title: 'User Overview' },
  { path: '/page/pricing-admin', title: 'Pricing' },
  { path: '/page/pricing', title: 'Pricing' },
  { path: '/page/help-center', title: 'Help Center' },
  { path: '/page/privacy-policy', title: 'Privacy Policy' },
  { path: '/page/faq', title: 'FAQ' },
  { path: '/page/licenses', title: 'Licenses' },
  { path: '/form/wizard-basic', title: 'Wizard Basic' },
  { path: '/apexchart/line', title: 'Line Chart' },
  { path: '/apexchart/heatmap', title: 'Heatmap Chart' },
  { path: '/apexchart/funnel', title: 'Funnel Chart' },
  { path: '/apexchart/column', title: 'Column Chart' },
  { path: '/apexchart/candlestick', title: 'Candlestick Chart' },
  { path: '/apexchart/bubble', title: 'Bubble Chart' },
  { path: '/apexchart/box-whisker', title: 'Box & Whisker Chart' },
  { path: '/apexchart/bar', title: 'Bar Chart' },
  { path: '/apexchart/area', title: 'Area Chart' },
  { path: '/apexchart/treemap', title: 'Treemap Chart' },
  { path: '/apexchart/timeline', title: 'Timeline Chart' },
  { path: '/apexchart/slope', title: 'Slope Chart' },
  { path: '/apexchart/scatter', title: 'Scatter Plot Chart' },
  { path: '/apexchart/range-area', title: 'Range Area Chart' },
  { path: '/apexchart/radialbar', title: 'Radial Bar Chart' },
  { path: '/apexchart/radar', title: 'Radar Chart' },
  { path: '/apexchart/polar-area', title: 'Polar Area Chart' },
  { path: '/apexchart/pie', title: 'Pie Chart' },
  { path: '/apexchart/mixed', title: 'Mixed Charts' },
  { path: '/apexsankey', title: 'Apexsankey Chart' },
  { path: '/maps/vector', title: 'Vector' },
  { path: '/maps/google', title: 'Google Map' },
  { path: '/echart/pie', title: 'Pie Charts' },
  { path: '/echart/line', title: 'Line Charts' },
  { path: '/echart/bar', title: 'Bar Charts' },
]
